// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prog1ef;

namespace prog1ef.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240406165631_efcore")]
    partial class efcore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("prog1ef.Department_and_name_manager", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deptnamemanger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Department_and_name_manager");
                });

            modelBuilder.Entity("prog1ef.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MoneyID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numberphone")
                        .HasColumnType("int");

                    b.Property<long>("SSN")
                        .HasMaxLength(14)
                        .HasColumnType("bigint");

                    b.Property<int>("depID")
                        .HasColumnType("int");

                    b.Property<float>("salary")
                        .HasColumnType("real");

                    b.Property<string>("sheft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MoneyID");

                    b.HasIndex("depID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("prog1ef.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("RegisterId")
                        .HasColumnType("int");

                    b.Property<long>("SSN")
                        .HasColumnType("bigint");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("prog1ef.Money", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Department_and_name_managerID")
                        .HasColumnType("int");

                    b.Property<long>("SSN")
                        .HasColumnType("bigint");

                    b.Property<int>("blus_salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Department_and_name_managerID");

                    b.ToTable("moneys");
                });

            modelBuilder.Entity("prog1ef.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Department_and_name_managerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Numberphone")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<long>("SSN")
                        .HasMaxLength(14)
                        .HasColumnType("bigint");

                    b.Property<string>("confirmpaswword")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Department_and_name_managerID");

                    b.ToTable("register");
                });

            modelBuilder.Entity("prog1ef.Employee", b =>
                {
                    b.HasOne("prog1ef.Money", "Money")
                        .WithMany()
                        .HasForeignKey("MoneyID");

                    b.HasOne("prog1ef.Department_and_name_manager", "dep")
                        .WithMany("emp")
                        .HasForeignKey("depID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dep");

                    b.Navigation("Money");
                });

            modelBuilder.Entity("prog1ef.Login", b =>
                {
                    b.HasOne("prog1ef.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("prog1ef.Money", b =>
                {
                    b.HasOne("prog1ef.Department_and_name_manager", null)
                        .WithMany("money")
                        .HasForeignKey("Department_and_name_managerID");
                });

            modelBuilder.Entity("prog1ef.Register", b =>
                {
                    b.HasOne("prog1ef.Department_and_name_manager", null)
                        .WithMany("register")
                        .HasForeignKey("Department_and_name_managerID");
                });

            modelBuilder.Entity("prog1ef.Department_and_name_manager", b =>
                {
                    b.Navigation("emp");

                    b.Navigation("money");

                    b.Navigation("register");
                });
#pragma warning restore 612, 618
        }
    }
}
